### ISSUE TITLE
DEB creator plugin

### ISSUE THREAD

**Issue by activey** [activey/bob-builder#3]
Implement a plugin for generating DEB file that could be shipped to debian/ubuntu distros.

**Comment by PerfectCarl** [comment]
I have some working templates [here](https://github.com/I-hate-farms/hen/tree/master/.hen/templates/debian) Feel free to steal whatever you like.

**Comment by PerfectCarl** [comment]
I have also experience on how to generate a local debian repository (that you can put on a web server as a deb repository url) if you ever wonder how this can be done...

**Comment by activey** [comment]
Yup, got it in my bookmarks already :)
What a pitty there is nothing like a libdeb with vapi bindings that it could be done usual way ;P

**Comment by activey** [comment]
Starting progress.

**Comment by PerfectCarl** [comment]
Good luck!

**Comment by activey** [comment]
So here it is ;) First rough version of debian package creator plugin is available here: https://github.com/activey/valder/tree/master/plugin-debian
