### ISSUE TITLE
semantic version for the deps

### ISSUE THREAD

**Issue by ensonic** [activey/bob-builder#36]
Maybe you can take some inspiration form package.json that is used with npm. E.g. the wait version for deps are specified:
https://github.com/npm/node-semver

**Comment by activey** [comment]
Hmm, let me understand the point ;) is it about json file structure? or is it something more behind? :)

**Comment by activey** [comment]
Yeah, that is probably about that, together with recognizing those ^ and ~. I'm afraid it wont make any much sense since on gnu/linux there is no particular standard regarding version naming ;( Or is it?

**Comment by ensonic** [comment]
The so name versioning is actually the same as the semantic versioning. The idea of the ticket was to suggest to also allow versions like >2.4, but now thinking about it again, that probably what you do any way. Closing the ticket and sorry for the noise. I guess I was doing to much npm and got carried away by json=json :)

**Comment by activey** [comment]
:)
