### ISSUE TITLE
Update documentation

### ISSUE THREAD

**Issue by activey** [activey/bob-builder#50]
Update online documentation, add:
1. Information about generating GIR file,
2. Info about "sources" in recipe file

**Comment by igarcez** [comment]
The installation proccess also needs to be updated, I only could use the 'bob' binary after running build-old.sh inside the 'plugins-' folders where the documantation tells me to run build.sh inside inexistents 'tool-' folders, and then running update-plugins.sh.

It also generated files not ignored by git, maybe it shouldn't?

I'm sorry if I misinterpreted  the docs.

**Comment by activey** [comment]
Right, there are some other discrepancies as well, will double check it.

**Comment by activey** [comment]
I've managed to fix and update some stuff, hopefuly now it matches better the current state.
