### ISSUE TITLE
Comparison with Poulp

### ISSUE THREAD

**Issue by SkyzohKey** [activey/bob-builder#57]
Currently [Poulp](https://framagit.org/Valse/poulp) provides almost everything Valder has + some other cool features, maybe add a comparison on the website next to the Bake (#32) one.

**Comment by activey** [comment]
Hi, first of all it's Valder, not Valser ;)
Just took a quick look at Poulp codebase. First big difference - Valder is plugin driven. In Poulp all the possible commands are hardcoded. From what I've seen in Poulp its code is rather ugly and hard to maintain. It's a matter of code maintenance and options for extending/introducing new features. When you take a look at Poulp code here in https://framagit.org/valse/poulp/blob/develop/src/commands/build.vala you can see that it runs valac process with set of params.
Here in Valder I've rewritten valac code completely and included it in plugin code. 

There are lot of other differences. Just compare our code bases.

And Valder has nicer home page ;)

**Comment by SkyzohKey** [comment]
Yeah I have to admit that your website looks cool guy, not criticism your work in any way. Sorry for the typo, I'm using a mobile device.

**Comment by activey** [comment]
No worries ;] Can I close it already? ;)

**Comment by SkyzohKey** [comment]
Done :)
